export const ALL_USER_REQUEST = "ALL_USER_REQUEST";
export const ALL_USER_SUCCESS = "ALL_USER_SUCCESS";
export const ALL_USER_FAIL = "ALL_USER_FAIL";
export const ALL_REGISTER_USER_REQUEST = "ALL_REGISTER_USER_REQUEST"
export const ALL_REGISTER_USER_SUCCESS = "ALL_REGISTER_USER_SUCCESS";
export const ALL_REGISTER_USER_FAIL = "ALL_REGISTER_USER_FAIL";
